#!/usr/bin/env python3
"""Hand-edited textures (D-020): PNG files that replace single GRAPH0/1/2 entries.

Usage: overrides.py check [overrides_dir] [orig_graph_dir]

Where they live (D-031). The hand-made PNGs of the project are committed in
<repo>/texture_overrides/ (they are edited artwork, never the original textures).
The directory searched is $KIMIKISS_OVERRIDES, else <repo>/texture_overrides, else
<repo>/../kimikiss-private/texture_overrides (or $KIMIKISS_PRIVATE_DIR/texture_overrides).
Any other directory inside the repository is refused unless git ignores it (build/).

Names. GRAPH0_0453.png = entry 453 of GRAPH0.ARC, GRAPH1_0058.png = entry 58 of
GRAPH1.ARC, the names `tools/extract/tim2.py topng` exports use. Every *.png in
the directory must be named that way; other files are ignored.

What a PNG may be. Any PNG Pillow can read (RGBA, RGB, grey, indexed, any bit
depth), exactly as wide and high as the original texture. The entry stays a
TIM2 with the original header, size, palette order and CSM1 layout, so the
ARC offsets do not move:
  * An indexed PNG whose palette has as many entries as the original palette
    (256 for every texture of the game) is taken literally: its indices and its
    palette (with tRNS) become the new picture and CLUT. This is what
    `tim2.py topng` writes, so editing in an indexed editor and changing the
    palette needs nothing else. The alpha convention of the original applies
    (PNG 0..255 <-> PS2 0..128 when every original alpha is <= 0x80, copied raw
    otherwise; D-008).
  * Anything else is converted to RGBA and mapped onto the *existing* palette:
    a pixel that equals the original pixel (same colour, or both clear) keeps its
    index; every other pixel gets the nearest of the palette entries the
    original picture uses (premultiplied RGB + alpha, the quantizer of redraw.py)
    and fully clear pixels the most common clear entry.
An override replaces the automatic redraw (labels.tsv) of its entry.

Refused with an explanation: wrong size, entry not in the archive, entry that
is not a TIM2 (GRAPH0 396, the float records of GRAPH2), the generated font
(GRAPH0 77), a 4bpp texture, two files for one entry.

Needs Pillow and numpy.
"""
import os
import re
import subprocess
import sys

try:
    import numpy as np
    from PIL import Image
except ImportError:
    raise SystemExit('tools/texture/overrides.py needs Pillow and numpy (pip install pillow numpy)')

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.realpath(os.path.join(HERE, '..', '..'))
sys.path[:0] = [HERE, os.path.join(HERE, '..', 'extract')]
import arc  # noqa: E402
import redraw  # noqa: E402
import tim2  # noqa: E402

ARCHIVES = ('GRAPH0', 'GRAPH1', 'GRAPH2')
NAME = re.compile(r'^(GRAPH[0-9])_(\d+)\.png$', re.I)
FONT = ('GRAPH0', 77)           # generated by tools/font, not a texture to hand-edit
CLOSE = 24.0                    # colour distance beyond which a mapped pixel is reported


class OverrideError(Exception):
    pass


def default_dir():
    """$KIMIKISS_OVERRIDES, else <repo>/texture_overrides, else ../kimikiss-private/texture_overrides."""
    d = os.environ.get('KIMIKISS_OVERRIDES')
    if d:
        return d
    local = os.path.join(REPO, 'texture_overrides')   # committed, next to build.bat
    if os.path.isdir(local):
        return local
    private = os.environ.get('KIMIKISS_PRIVATE_DIR') or os.path.join(os.path.dirname(REPO), 'kimikiss-private')
    return os.path.join(private, 'texture_overrides')


def _check_outside_repo(directory):
    real = os.path.realpath(directory)
    if os.path.commonpath([real, REPO]) != REPO:
        return
    if real == os.path.join(REPO, 'texture_overrides'):
        return   # the project's own hand-made textures (D-031)
    try:
        ignored = subprocess.run(['git', '-C', REPO, 'check-ignore', '-q', real],
                                 stderr=subprocess.DEVNULL).returncode == 0
    except OSError:
        ignored = real.startswith(os.path.join(REPO, 'build') + os.sep)
    if not ignored:
        raise OverrideError(f'{directory} is inside the repository and not ignored by git: textures other than '
                            'the project\'s texture_overrides/ must stay outside (default ../kimikiss-private/texture_overrides, '
                            'or set KIMIKISS_OVERRIDES)')


def find(directory=None):
    """-> {archive: {entry: path}} for every PNG of the directory (none if the default directory is absent)."""
    explicit = directory is not None or 'KIMIKISS_OVERRIDES' in os.environ
    directory = directory or default_dir()
    if not os.path.isdir(directory):
        if explicit:
            raise OverrideError(f'overrides directory {directory} does not exist')
        return {}
    _check_outside_repo(directory)
    found, seen = {}, {}
    for fn in sorted(os.listdir(directory)):
        if not fn.lower().endswith('.png'):
            continue
        m = NAME.match(fn)
        if not m or m.group(1).upper() not in ARCHIVES:
            raise OverrideError(f'{fn}: not a texture name; expected GRAPH0_NNNN.png, GRAPH1_NNNN.png or '
                                f'GRAPH2_NNNN.png (entry number as in tim2.py topng)')
        key = (m.group(1).upper(), int(m.group(2)))
        if key in seen:
            raise OverrideError(f'{fn} and {seen[key]} are both {key[0]} entry {key[1]}')
        seen[key] = fn
        found.setdefault(key[0], {})[key[1]] = os.path.join(directory, fn)
    return found


def _rgba(im):
    """Pillow image -> uint8 (h, w, 4) RGBA array, for any mode."""
    if im.mode.startswith('I') or im.mode == 'F':            # 16/32-bit grey
        a = np.asarray(im, dtype=np.float64)
        a = a / 257 if a.max() > 255 else a
        im = Image.fromarray(np.clip(a + 0.5, 0, 255).astype(np.uint8), 'L')
    if im.mode == 'CMYK' or im.mode == 'YCbCr' or im.mode == 'LAB' or im.mode == 'HSV':
        im = im.convert('RGB')
    return np.asarray(im.convert('RGBA'))


def _indexed_palette(im, n):
    """(rgb (n, 3), alpha (n,)) of an indexed image, or None when the palette has other than n entries."""
    if im.mode != 'P' or im.palette is None or im.palette.mode != 'RGB':
        return None
    raw = im.palette.palette
    if len(raw) // 3 != n:
        return None
    rgb = np.frombuffer(bytes(raw[:3 * n]), np.uint8).reshape(n, 3)
    tr = im.info.get('transparency')
    alpha = np.full(n, 255, np.uint8)
    if isinstance(tr, int):
        alpha[tr] = 0
    elif isinstance(tr, (bytes, bytearray)):
        alpha[:len(tr)] = np.frombuffer(bytes(tr[:n]), np.uint8)
    return rgb, alpha


def to_tim2(png_path, blob, label=''):
    """Convert one PNG to the TIM2 `blob` replaces. -> (new TIM2 bytes, info dict)."""
    label = label or os.path.basename(png_path)
    if blob[:4] != b'TIM2':
        raise OverrideError(f'{label}: the entry is not a TIM2 texture')
    t = tim2.parse(blob)
    if t['bpp'] != 8:
        raise OverrideError(f'{label}: only 8bpp textures can be replaced ({t["bpp"]}bpp)')
    w, h = t['w'], t['h']
    try:
        im = Image.open(png_path)
        im.load()
    except Exception as e:                                  # noqa: BLE001 - Pillow raises many types
        raise OverrideError(f'{label}: cannot read PNG ({e})') from e
    if im.size != (w, h):
        raise OverrideError(f'{label}: PNG is {im.size[0]} x {im.size[1]}, the texture is {w} x {h}; '
                            'the size must not change')
    n = len(t['palette'])
    pal = np.array(t['palette'], np.int64)
    scaled = bool((pal[:, 3] <= 0x80).all())                # D-008: alpha scaled 0x80 -> 255 when all <= 0x80
    pal_png_a = np.array([tim2.alpha_to_png(int(a)) if scaled else int(a) for a in pal[:, 3]], np.int64)
    info = {'mode': 'palette', 'warnings': []}
    indexed = _indexed_palette(im, n)
    if indexed is not None:
        rgb, a = indexed
        ps2_a = [tim2.alpha_from_png(int(x)) if scaled else int(x) for x in a]
        palette = [tuple(int(v) for v in rgb[i]) + (ps2_a[i],) for i in range(n)]
        indices = np.asarray(im, np.uint8).tobytes()
        if 'transparency' not in im.info and (pal_png_a < 255).any():
            info['warnings'].append('indexed PNG has no transparency (tRNS) but the original palette does')
        out = tim2.build(t['header'], w, h, t['bpp'], t['swizzled'], palette, indices)
        info['changed'] = int((np.frombuffer(indices, np.uint8) != np.frombuffer(t['indices'], np.uint8)).sum())
        info['new_palette'] = palette != t['palette']
        return _checked(out, blob, label), info

    # RGBA path: map onto the existing palette
    info['mode'] = 'quantized'
    px = _rgba(im).reshape(-1, 4).astype(np.int64)
    old = np.frombuffer(t['indices'], np.uint8)
    old_rgba = np.concatenate([pal[:, :3], pal_png_a[:, None]], axis=1)[old]
    same = (px[:, 3] == old_rgba[:, 3]) & ((px[:, 3] == 0) | (px[:, :3] == old_rgba[:, :3]).all(1))
    new = old.copy()
    todo = np.flatnonzero(~same)
    info['changed'] = len(todo)
    info['max_err'] = 0.0
    info['far'] = 0
    if len(todo):
        tex = redraw.Tex(blob)
        cand = tex.cand
        cp_rgb, cp_a = pal[cand, :3].astype(float), pal_png_a[cand] / 255.0
        packed = (px[todo] * np.array([1 << 24, 1 << 16, 1 << 8, 1])).sum(1)
        uniq, first, inv = np.unique(packed, return_index=True, return_inverse=True)
        u = px[todo][first]
        t_a = u[:, 3] / 255.0
        pick, dist = redraw.nearest_palette(u[:, :3].astype(float), t_a, cp_rgb, cp_a)
        idx = cand[pick]
        if tex.clear_idx is not None:
            idx = np.where(t_a < 0.02, tex.clear_idx, idx)
            dist = np.where(t_a < 0.02, 0.0, dist)
        new[todo] = idx[inv]
        d = dist[inv]
        info['max_err'] = round(float(d.max()), 1)
        info['far'] = int((d > CLOSE).sum())
        if info['far']:
            info['warnings'].append(
                f'{info["far"]} of {len(todo)} changed pixels are more than {CLOSE:.0f} off the nearest palette '
                f'colour (worst {info["max_err"]}); save an indexed PNG with the full {n}-colour palette to use '
                'new colours')
    out = tim2.build(t['header'], w, h, t['bpp'], t['swizzled'], t['palette'], new.tobytes())
    return _checked(out, blob, label), info


def _checked(out, blob, label):
    if len(out) != len(blob) or out[:64] != blob[:64]:
        raise OverrideError(f'{label}: converted TIM2 differs in length or header from the original')
    return out


def convert(arc_data, archive, found, report=None):
    """Convert the overrides of one archive. -> {entry: new TIM2 bytes}, [info dicts]."""
    a = arc.parse(arc_data)
    blobs, infos = {}, []
    for entry, path in sorted(found.items()):
        label = f'{os.path.basename(path)}'
        if entry >= a['count']:
            raise OverrideError(f'{label}: {archive} has {a["count"]} entries (0..{a["count"] - 1}); '
                                f'there is no entry {entry}')
        if (archive, entry) == FONT:
            raise OverrideError(f'{label}: GRAPH0 entry 77 is the dialogue font, generated from '
                                'tools/font/en_font.pgm; it cannot be overridden by a PNG')
        e = a['entries'][entry]
        blob = bytes(arc_data[e['offset']:e['offset'] + e['size']])
        out, info = to_tim2(path, blob, label)
        info.update(archive=archive, entry=entry, file=os.path.basename(path))
        blobs[entry] = out
        infos.append(info)
    return blobs, infos


def describe(info):
    s = f'{info["archive"]}_{info["entry"]:04d}: {info["file"]}, {info["mode"]}, {info["changed"]} pixels differ'
    if info['mode'] == 'palette' and info.get('new_palette'):
        s += ', new palette'
    if info['mode'] == 'quantized' and info['changed']:
        s += f', worst colour error {info["max_err"]}'
    return s


def main():
    if len(sys.argv) < 2 or sys.argv[1] != 'check':
        sys.exit(__doc__)
    directory = sys.argv[2] if len(sys.argv) > 2 else None
    graph = sys.argv[3] if len(sys.argv) > 3 else os.path.join(REPO, 'build', 'orig', 'GRAPH')
    try:
        found = find(directory)
        if not found:
            print(f'no overrides in {directory or default_dir()}')
            return
        import mmap
        for name, entries in sorted(found.items()):
            with open(os.path.join(graph, name + '.ARC'), 'rb') as f:
                data = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
                _, infos = convert(data, name, entries)
            for info in infos:
                print(describe(info))
                for w in info['warnings']:
                    print('  warning:', w)
    except OverrideError as e:
        sys.exit(f'error: {e}')


if __name__ == '__main__':
    main()
